// ─── MARKETLENS STOCK UNIVERSE ───
// 250 stocks across NSE and BSE
// idx: nifty50 | nifty100 | nifty200 | bse100 | midcap | smallcap
window.STOCK_UNIVERSE = [
  // ══ NIFTY 50 ══
  {t:'RELIANCE.NS',  n:'Reliance Industries',       s:'Energy',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'TCS.NS',       n:'Tata Consultancy Services',  s:'IT',            e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'HDFCBANK.NS',  n:'HDFC Bank',                  s:'Banking',       e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'INFY.NS',      n:'Infosys',                    s:'IT',            e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'ICICIBANK.NS', n:'ICICI Bank',                 s:'Banking',       e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'HINDUNILVR.NS',n:'Hindustan Unilever',         s:'FMCG',          e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'BAJFINANCE.NS',n:'Bajaj Finance',              s:'Finance',       e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'KOTAKBANK.NS', n:'Kotak Mahindra Bank',        s:'Banking',       e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'LT.NS',        n:'Larsen & Toubro',            s:'Infrastructure',e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'WIPRO.NS',     n:'Wipro',                      s:'IT',            e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'AXISBANK.NS',  n:'Axis Bank',                  s:'Banking',       e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'SUNPHARMA.NS', n:'Sun Pharma',                 s:'Pharma',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'MARUTI.NS',    n:'Maruti Suzuki',              s:'Auto',          e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'TITAN.NS',     n:'Titan Company',              s:'Consumer',      e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'NESTLEIND.NS', n:'Nestle India',               s:'FMCG',          e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'TATASTEEL.NS', n:'Tata Steel',                 s:'Metals',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'ONGC.NS',      n:'ONGC',                       s:'Energy',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'POWERGRID.NS', n:'Power Grid Corp',            s:'Utilities',     e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'ADANIPORTS.NS',n:'Adani Ports',                s:'Infrastructure',e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'HCLTECH.NS',   n:'HCL Technologies',           s:'IT',            e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'DRREDDY.NS',   n:'Dr Reddys Labs',             s:'Pharma',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'TATAMOTORS.NS',n:'Tata Motors',                s:'Auto',          e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'BAJAJFINSV.NS',n:'Bajaj Finserv',              s:'Finance',       e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'SBIN.NS',      n:'State Bank of India',        s:'Banking',       e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'DIVISLAB.NS',  n:'Divis Laboratories',         s:'Pharma',        e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'HEROMOTOCO.NS',n:'Hero MotoCorp',              s:'Auto',          e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'CIPLA.NS',     n:'Cipla',                      s:'Pharma',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'COALINDIA.NS', n:'Coal India',                 s:'Mining',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'EICHERMOT.NS', n:'Eicher Motors',              s:'Auto',          e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'ULTRACEMCO.NS',n:'UltraTech Cement',           s:'Cement',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'JSWSTEEL.NS',  n:'JSW Steel',                  s:'Metals',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'NTPC.NS',      n:'NTPC',                       s:'Utilities',     e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'GRASIM.NS',    n:'Grasim Industries',          s:'Cement',        e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'TECHM.NS',     n:'Tech Mahindra',              s:'IT',            e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'ASIANPAINT.NS',n:'Asian Paints',               s:'Consumer',      e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'M&M.NS',       n:'Mahindra & Mahindra',        s:'Auto',          e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'BAJAJ-AUTO.NS',n:'Bajaj Auto',                 s:'Auto',          e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'BRITANNIA.NS', n:'Britannia Industries',       s:'FMCG',          e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'APOLLOHOSP.NS',n:'Apollo Hospitals',           s:'Healthcare',    e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'INDUSINDBK.NS',n:'IndusInd Bank',              s:'Banking',       e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'BPCL.NS',      n:'BPCL',                       s:'Energy',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'TATACONSUM.NS',n:'Tata Consumer Products',     s:'FMCG',          e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'ADANIENT.NS',  n:'Adani Enterprises',          s:'Conglomerate',  e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'HINDALCO.NS',  n:'Hindalco Industries',        s:'Metals',        e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'ITC.NS',       n:'ITC',                        s:'FMCG',          e:'NSE', idx:['nifty50','nifty100','nifty200','bse100']},
  {t:'SBILIFE.NS',   n:'SBI Life Insurance',         s:'Insurance',     e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'HDFCLIFE.NS',  n:'HDFC Life Insurance',        s:'Insurance',     e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'SHREECEM.NS',  n:'Shree Cement',               s:'Cement',        e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'UPL.NS',       n:'UPL',                        s:'Chemicals',     e:'NSE', idx:['nifty50','nifty100','nifty200']},
  {t:'BHARTIARTL.NS',n:'Bharti Airtel',              s:'Telecom',       e:'NSE', idx:['nifty50','nifty100','nifty200']},
  // ══ NIFTY 100 ADDITIONS ══
  {t:'ZOMATO.NS',    n:'Zomato',                     s:'Consumer Tech', e:'NSE', idx:['nifty100','nifty200']},
  {t:'PIDILITIND.NS',n:'Pidilite Industries',        s:'Chemicals',     e:'NSE', idx:['nifty100','nifty200']},
  {t:'DABUR.NS',     n:'Dabur India',                s:'FMCG',          e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'SIEMENS.NS',   n:'Siemens',                    s:'Industrials',   e:'NSE', idx:['nifty100','nifty200']},
  {t:'HAVELLS.NS',   n:'Havells India',              s:'Electricals',   e:'NSE', idx:['nifty100','nifty200']},
  {t:'DMART.NS',     n:'Avenue Supermarts (DMart)',  s:'Retail',        e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'TRENT.NS',     n:'Trent',                      s:'Retail',        e:'NSE', idx:['nifty100','nifty200']},
  {t:'BANKBARODA.NS',n:'Bank of Baroda',             s:'Banking',       e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'ICICIPRULI.NS',n:'ICICI Pru Life Insurance',   s:'Insurance',     e:'NSE', idx:['nifty100','nifty200']},
  {t:'NAUKRI.NS',    n:'Info Edge (Naukri)',          s:'IT',            e:'NSE', idx:['nifty100','nifty200']},
  {t:'PNB.NS',       n:'Punjab National Bank',       s:'Banking',       e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'VEDL.NS',      n:'Vedanta',                    s:'Metals',        e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'BEL.NS',       n:'Bharat Electronics',         s:'Defence',       e:'NSE', idx:['nifty100','nifty200']},
  {t:'MARICO.NS',    n:'Marico',                     s:'FMCG',          e:'NSE', idx:['nifty100','nifty200']},
  {t:'COLPAL.NS',    n:'Colgate-Palmolive India',    s:'FMCG',          e:'NSE', idx:['nifty100','nifty200']},
  {t:'AMBUJACEM.NS', n:'Ambuja Cements',             s:'Cement',        e:'NSE', idx:['nifty100','nifty200']},
  {t:'GODREJCP.NS',  n:'Godrej Consumer Products',   s:'FMCG',          e:'NSE', idx:['nifty100','nifty200']},
  {t:'DLF.NS',       n:'DLF',                        s:'Real Estate',   e:'NSE', idx:['nifty100','nifty200']},
  {t:'INDIGO.NS',    n:'IndiGo (InterGlobe Aviation)',s:'Aviation',     e:'NSE', idx:['nifty100','nifty200']},
  {t:'TATAPOWER.NS', n:'Tata Power',                 s:'Utilities',     e:'NSE', idx:['nifty100','nifty200']},
  {t:'HINDPETRO.NS', n:'HPCL',                       s:'Energy',        e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'GAIL.NS',      n:'GAIL India',                 s:'Energy',        e:'NSE', idx:['nifty100','nifty200','bse100']},
  {t:'CANBK.NS',     n:'Canara Bank',                s:'Banking',       e:'NSE', idx:['nifty100','nifty200']},
  {t:'MUTHOOTFIN.NS',n:'Muthoot Finance',            s:'Finance',       e:'NSE', idx:['nifty100','nifty200']},
  {t:'BERGEPAINT.NS',n:'Berger Paints',              s:'Consumer',      e:'NSE', idx:['nifty100','nifty200']},
  {t:'TORNTPHARM.NS',n:'Torrent Pharma',             s:'Pharma',        e:'NSE', idx:['nifty100','nifty200']},
  {t:'BAJAJHLDNG.NS',n:'Bajaj Holdings',             s:'Finance',       e:'NSE', idx:['nifty100','nifty200']},
  {t:'ICICIGI.NS',   n:'ICICI Lombard General Ins',  s:'Insurance',     e:'NSE', idx:['nifty100','nifty200']},
  {t:'MCDOWELL-N.NS',n:'United Spirits',             s:'Consumer',      e:'NSE', idx:['nifty100','nifty200']},
  // ══ NIFTY 200 ADDITIONS ══
  {t:'AUBANK.NS',    n:'AU Small Finance Bank',      s:'Banking',       e:'NSE', idx:['nifty200']},
  {t:'AUROPHARMA.NS',n:'Aurobindo Pharma',           s:'Pharma',        e:'NSE', idx:['nifty200']},
  {t:'BANDHANBNK.NS',n:'Bandhan Bank',               s:'Banking',       e:'NSE', idx:['nifty200']},
  {t:'BOSCHLTD.NS',  n:'Bosch',                      s:'Auto',          e:'NSE', idx:['nifty200']},
  {t:'CHOLAFIN.NS',  n:'Cholamandalam Investment',   s:'Finance',       e:'NSE', idx:['nifty200']},
  {t:'FEDERALBNK.NS',n:'Federal Bank',               s:'Banking',       e:'NSE', idx:['nifty200']},
  {t:'GODREJPROP.NS',n:'Godrej Properties',          s:'Real Estate',   e:'NSE', idx:['nifty200']},
  {t:'HAL.NS',       n:'Hindustan Aeronautics',      s:'Defence',       e:'NSE', idx:['nifty200']},
  {t:'IDFCFIRSTB.NS',n:'IDFC First Bank',            s:'Banking',       e:'NSE', idx:['nifty200']},
  {t:'IRCTC.NS',     n:'IRCTC',                      s:'Travel',        e:'NSE', idx:['nifty200']},
  {t:'JUBLFOOD.NS',  n:'Jubilant Foodworks',         s:'Consumer',      e:'NSE', idx:['nifty200']},
  {t:'LICHSGFIN.NS', n:'LIC Housing Finance',        s:'Finance',       e:'NSE', idx:['nifty200']},
  {t:'LICI.NS',      n:'LIC of India',               s:'Insurance',     e:'NSE', idx:['nifty200']},
  {t:'LUPIN.NS',     n:'Lupin',                      s:'Pharma',        e:'NSE', idx:['nifty200']},
  {t:'NHPC.NS',      n:'NHPC',                       s:'Utilities',     e:'NSE', idx:['nifty200']},
  {t:'NMDC.NS',      n:'NMDC',                       s:'Mining',        e:'NSE', idx:['nifty200']},
  {t:'OBEROIRLTY.NS',n:'Oberoi Realty',              s:'Real Estate',   e:'NSE', idx:['nifty200']},
  {t:'OIL.NS',       n:'Oil India',                  s:'Energy',        e:'NSE', idx:['nifty200']},
  {t:'PAGEIND.NS',   n:'Page Industries',            s:'Consumer',      e:'NSE', idx:['nifty200']},
  {t:'PERSISTENT.NS',n:'Persistent Systems',         s:'IT',            e:'NSE', idx:['nifty200']},
  {t:'PETRONET.NS',  n:'Petronet LNG',               s:'Energy',        e:'NSE', idx:['nifty200']},
  {t:'POLYCAB.NS',   n:'Polycab India',              s:'Electricals',   e:'NSE', idx:['nifty200']},
  {t:'RECLTD.NS',    n:'REC',                        s:'Finance',       e:'NSE', idx:['nifty200']},
  {t:'SAIL.NS',      n:'SAIL',                       s:'Metals',        e:'NSE', idx:['nifty200']},
  {t:'SRF.NS',       n:'SRF',                        s:'Chemicals',     e:'NSE', idx:['nifty200']},
  {t:'SUNTV.NS',     n:'Sun TV Network',             s:'Media',         e:'NSE', idx:['nifty200']},
  {t:'TATACHEM.NS',  n:'Tata Chemicals',             s:'Chemicals',     e:'NSE', idx:['nifty200']},
  {t:'TATAELXSI.NS', n:'Tata Elxsi',                 s:'IT',            e:'NSE', idx:['nifty200']},
  {t:'VOLTAS.NS',    n:'Voltas',                     s:'Electricals',   e:'NSE', idx:['nifty200']},
  {t:'PFC.NS',       n:'Power Finance Corp',         s:'Finance',       e:'NSE', idx:['nifty200']},
  {t:'MOTHERSON.NS', n:'Samvardhana Motherson',      s:'Auto',          e:'NSE', idx:['nifty200']},
  {t:'BHEL.NS',      n:'Bharat Heavy Electricals',   s:'Industrials',   e:'NSE', idx:['nifty200']},
  {t:'CONCOR.NS',    n:'Container Corporation',      s:'Logistics',     e:'NSE', idx:['nifty200']},
  {t:'CUMMINSIND.NS',n:'Cummins India',              s:'Industrials',   e:'NSE', idx:['nifty200']},
  {t:'JSWENERGY.NS', n:'JSW Energy',                 s:'Utilities',     e:'NSE', idx:['nifty200']},
  {t:'BHARATFORG.NS',n:'Bharat Forge',               s:'Auto',          e:'NSE', idx:['nifty200']},
  {t:'SUNDARMFIN.NS',n:'Sundaram Finance',           s:'Finance',       e:'NSE', idx:['nifty200']},
  {t:'WHIRLPOOL.NS', n:'Whirlpool of India',         s:'Consumer',      e:'NSE', idx:['nifty200']},
  // ══ MIDCAP ══
  {t:'ABCAPITAL.NS', n:'Aditya Birla Capital',       s:'Finance',       e:'NSE', idx:['midcap']},
  {t:'ACC.NS',       n:'ACC',                        s:'Cement',        e:'NSE', idx:['midcap']},
  {t:'ALKEM.NS',     n:'Alkem Laboratories',         s:'Pharma',        e:'NSE', idx:['midcap']},
  {t:'ASTRAL.NS',    n:'Astral',                     s:'Industrials',   e:'NSE', idx:['midcap']},
  {t:'BALKRISIND.NS',n:'Balkrishna Industries',      s:'Auto',          e:'NSE', idx:['midcap']},
  {t:'BATAINDIA.NS', n:'Bata India',                 s:'Consumer',      e:'NSE', idx:['midcap']},
  {t:'BIOCON.NS',    n:'Biocon',                     s:'Pharma',        e:'NSE', idx:['midcap']},
  {t:'CANFINHOME.NS',n:'Can Fin Homes',              s:'Finance',       e:'NSE', idx:['midcap']},
  {t:'CROMPTON.NS',  n:'Crompton Greaves Consumer',  s:'Electricals',   e:'NSE', idx:['midcap']},
  {t:'DEEPAKNTR.NS', n:'Deepak Nitrite',             s:'Chemicals',     e:'NSE', idx:['midcap']},
  {t:'DIXON.NS',     n:'Dixon Technologies',         s:'Electronics',   e:'NSE', idx:['midcap']},
  {t:'GLENMARK.NS',  n:'Glenmark Pharma',            s:'Pharma',        e:'NSE', idx:['midcap']},
  {t:'HINDZINC.NS',  n:'Hindustan Zinc',             s:'Metals',        e:'NSE', idx:['midcap']},
  {t:'INDHOTEL.NS',  n:'Indian Hotels',              s:'Hospitality',   e:'NSE', idx:['midcap']},
  {t:'JKCEM.NS',     n:'JK Cement',                  s:'Cement',        e:'NSE', idx:['midcap']},
  {t:'LAURUSLABS.NS',n:'Laurus Labs',                s:'Pharma',        e:'NSE', idx:['midcap']},
  {t:'MAXHEALTH.NS', n:'Max Healthcare',             s:'Healthcare',    e:'NSE', idx:['midcap']},
  {t:'MGL.NS',       n:'Mahanagar Gas',              s:'Energy',        e:'NSE', idx:['midcap']},
  {t:'MPHASIS.NS',   n:'Mphasis',                    s:'IT',            e:'NSE', idx:['midcap']},
  {t:'OFSS.NS',      n:'Oracle Financial Services',  s:'IT',            e:'NSE', idx:['midcap']},
  {t:'PIIND.NS',     n:'PI Industries',              s:'Chemicals',     e:'NSE', idx:['midcap']},
  {t:'RAMCOCEM.NS',  n:'Ramco Cements',              s:'Cement',        e:'NSE', idx:['midcap']},
  {t:'SUPREMEIND.NS',n:'Supreme Industries',         s:'Industrials',   e:'NSE', idx:['midcap']},
  {t:'TORNTPOWER.NS',n:'Torrent Power',              s:'Utilities',     e:'NSE', idx:['midcap']},
  {t:'TVSMOTOR.NS',  n:'TVS Motor',                  s:'Auto',          e:'NSE', idx:['midcap']},
  {t:'UBL.NS',       n:'United Breweries',           s:'Consumer',      e:'NSE', idx:['midcap']},
  {t:'UNIONBANK.NS', n:'Union Bank of India',        s:'Banking',       e:'NSE', idx:['midcap']},
  {t:'LTTS.NS',      n:'L&T Technology Services',    s:'IT',            e:'NSE', idx:['midcap']},
  {t:'LALPATHLAB.NS',n:'Dr Lal PathLabs',            s:'Healthcare',    e:'NSE', idx:['midcap']},
  {t:'ABFRL.NS',     n:'Aditya Birla Fashion',       s:'Retail',        e:'NSE', idx:['midcap']},
  {t:'SYNGENE.NS',   n:'Syngene International',      s:'Pharma',        e:'NSE', idx:['midcap']},
  {t:'IPCALAB.NS',   n:'IPCA Laboratories',          s:'Pharma',        e:'NSE', idx:['midcap']},
  {t:'CESC.NS',      n:'CESC',                       s:'Utilities',     e:'NSE', idx:['midcap']},
  {t:'EXIDEIND.NS',  n:'Exide Industries',           s:'Auto',          e:'NSE', idx:['midcap']},
  {t:'SOBHA.NS',     n:'Sobha',                      s:'Real Estate',   e:'NSE', idx:['midcap']},
  {t:'PRESTIGE.NS',  n:'Prestige Estates',           s:'Real Estate',   e:'NSE', idx:['midcap']},
  {t:'PHOENIXLTD.NS',n:'Phoenix Mills',              s:'Real Estate',   e:'NSE', idx:['midcap']},
  {t:'SCHAEFFLER.NS',n:'Schaeffler India',           s:'Auto',          e:'NSE', idx:['midcap']},
  {t:'STAR.NS',      n:'Star Health Insurance',      s:'Insurance',     e:'NSE', idx:['midcap']},
  {t:'METROPOLIS.NS',n:'Metropolis Healthcare',      s:'Healthcare',    e:'NSE', idx:['midcap']},
  {t:'ESCORTS.NS',   n:'Escorts Kubota',             s:'Auto',          e:'NSE', idx:['midcap']},
  // ══ SMALLCAP ══
  {t:'AARTIIND.NS',  n:'Aarti Industries',           s:'Chemicals',     e:'NSE', idx:['smallcap']},
  {t:'AAVAS.NS',     n:'Aavas Financiers',           s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'ANGELONE.NS',  n:'Angel One',                  s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'APTUS.NS',     n:'Aptus Value Housing',        s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'BALRAMCHIN.NS',n:'Balrampur Chini Mills',      s:'FMCG',          e:'NSE', idx:['smallcap']},
  {t:'CDSL.NS',      n:'CDSL',                       s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'DELHIVERY.NS', n:'Delhivery',                  s:'Logistics',     e:'NSE', idx:['smallcap']},
  {t:'EMAMILTD.NS',  n:'Emami',                      s:'FMCG',          e:'NSE', idx:['smallcap']},
  {t:'FINEORG.NS',   n:'Fine Organic Industries',    s:'Chemicals',     e:'NSE', idx:['smallcap']},
  {t:'GHCL.NS',      n:'GHCL',                       s:'Chemicals',     e:'NSE', idx:['smallcap']},
  {t:'INDIAMART.NS', n:'IndiaMART InterMESH',        s:'IT',            e:'NSE', idx:['smallcap']},
  {t:'INTELLECT.NS', n:'Intellect Design Arena',     s:'IT',            e:'NSE', idx:['smallcap']},
  {t:'IRFC.NS',      n:'Indian Railway Finance Corp',s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'IEX.NS',       n:'Indian Energy Exchange',     s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'JYOTHYLAB.NS', n:'Jyothy Labs',                s:'FMCG',          e:'NSE', idx:['smallcap']},
  {t:'KPITTECH.NS',  n:'KPIT Technologies',          s:'IT',            e:'NSE', idx:['smallcap']},
  {t:'MEDANTA.NS',   n:'Global Health (Medanta)',    s:'Healthcare',    e:'NSE', idx:['smallcap']},
  {t:'NATCOPHARM.NS',n:'Natco Pharma',               s:'Pharma',        e:'NSE', idx:['smallcap']},
  {t:'NYKAA.NS',     n:'FSN E-Commerce (Nykaa)',     s:'Consumer Tech', e:'NSE', idx:['smallcap']},
  {t:'PAYTM.NS',     n:'One97 Communications (Paytm)',s:'Fintech',      e:'NSE', idx:['smallcap']},
  {t:'PNBHOUSING.NS',n:'PNB Housing Finance',        s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'POLICYBZR.NS', n:'PB Fintech (PolicyBazaar)',  s:'Fintech',       e:'NSE', idx:['smallcap']},
  {t:'RBLBANK.NS',   n:'RBL Bank',                   s:'Banking',       e:'NSE', idx:['smallcap']},
  {t:'SBICARD.NS',   n:'SBI Cards & Payment',        s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'SUMICHEM.NS',  n:'Sumitomo Chemical India',    s:'Chemicals',     e:'NSE', idx:['smallcap']},
  {t:'TANLA.NS',     n:'Tanla Platforms',            s:'IT',            e:'NSE', idx:['smallcap']},
  {t:'THYROCARE.NS', n:'Thyrocare Technologies',     s:'Healthcare',    e:'NSE', idx:['smallcap']},
  {t:'VMART.NS',     n:'V-Mart Retail',              s:'Retail',        e:'NSE', idx:['smallcap']},
  {t:'KAYNES.NS',    n:'Kaynes Technology',          s:'Electronics',   e:'NSE', idx:['smallcap']},
  {t:'BIKAJI.NS',    n:'Bikaji Foods',               s:'FMCG',          e:'NSE', idx:['smallcap']},
  {t:'HFCL.NS',      n:'HFCL',                       s:'Telecom',       e:'NSE', idx:['smallcap']},
  {t:'TRIDENT.NS',   n:'Trident',                    s:'Consumer',      e:'NSE', idx:['smallcap']},
  {t:'ANANTRAJ.NS',  n:'Anant Raj',                  s:'Real Estate',   e:'NSE', idx:['smallcap']},
  {t:'RVNL.NS',      n:'Rail Vikas Nigam',           s:'Infrastructure',e:'NSE', idx:['smallcap']},
  {t:'ROUTE.NS',     n:'Route Mobile',               s:'IT',            e:'NSE', idx:['smallcap']},
  {t:'ABSLAMC.NS',   n:'Aditya Birla AMC',           s:'Finance',       e:'NSE', idx:['smallcap']},
  {t:'CLEAN.NS',     n:'Clean Science & Technology', s:'Chemicals',     e:'NSE', idx:['smallcap']},
  // ══ BSE 100 EXCLUSIVES ══
  {t:'532978.BO',    n:'Bharti Airtel (BSE)',        s:'Telecom',       e:'BSE', idx:['bse100']},
  {t:'500010.BO',    n:'Housing Dev Finance (BSE)',  s:'Finance',       e:'BSE', idx:['bse100']},
  {t:'500696.BO',    n:'Hindustan Unilever (BSE)',   s:'FMCG',          e:'BSE', idx:['bse100']},
  {t:'500875.BO',    n:'ITC (BSE)',                  s:'FMCG',          e:'BSE', idx:['bse100']},
  {t:'500570.BO',    n:'Tata Motors (BSE)',          s:'Auto',          e:'BSE', idx:['bse100']},
  {t:'500400.BO',    n:'Tata Power (BSE)',           s:'Utilities',     e:'BSE', idx:['bse100']},
  {t:'500547.BO',    n:'GAIL India (BSE)',           s:'Energy',        e:'BSE', idx:['bse100']},
  {t:'507685.BO',    n:'Wipro (BSE)',                s:'IT',            e:'BSE', idx:['bse100']},
  {t:'500470.BO',    n:'Tata Steel (BSE)',           s:'Metals',        e:'BSE', idx:['bse100']},
  {t:'500312.BO',    n:'ONGC (BSE)',                 s:'Energy',        e:'BSE', idx:['bse100']},
];